resource: ./resources/
workdir: /tmp/na_dwd/


# How many hours will an archive file be retained in local database. Suggested
# to set this using following formula:
#   archive-life = (interval of data release) + (delay of each data release)
#
# For ICON dataset from Deutscher Wetterdienst, data is released every day on
# UTC time 00, 06, 12, 18 hours, so the interval is 6 hours. We will wait
# additional 3 hours after each release time so that data is available on DWD's
# server, so the delay is 3 hours.
archive-life: 9
